# Generated by Django 3.1.1 on 2021-07-25 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updates_at', models.DateField(auto_now_add=True)),
                ('remain_amt', models.IntegerField(blank=True, null=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.employee')),
            ],
        ),
    ]
