# Generated by Django 3.1.1 on 2021-07-25 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_amountdistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCosted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_amount', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updates_at', models.DateField(auto_now_add=True)),
                ('remain_amt', models.IntegerField(blank=True, null=True)),
                ('purchased', models.TextField(blank=True, max_length=200, null=True)),
                ('user_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.employee')),
                ('user_transtion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.amountdistribution')),
            ],
        ),
    ]
